CREATE DATABASE IF NOT EXISTS games;
USE games;

CREATE TABLE IF NOT EXISTS games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cost INT NOT NULL,
    category VARCHAR(255) NOT NULL
);
