services:
  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: song
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    container_name: backend
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: music_app
    depends_on:
      - database
    networks:
      - app-network
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.nginx
    container_name: frontend
    environment:
      REACT_APP_BACKEND_URL: http://backend:3001
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
